// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq5K_4mLFw9APtVpQhZrp_Z0wgL8P21W0',
    appId: '1:286337204652:web:40e32bb24c9804ba47ba09',
    messagingSenderId: '286337204652',
    projectId: 'smarttravel-b1d56',
    authDomain: 'smarttravel-b1d56.firebaseapp.com',
    storageBucket: 'smarttravel-b1d56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO_K0b0LitbDKklsHF8M-uWPDKUunNl1w',
    appId: '1:286337204652:android:a2a1595639573a5c47ba09',
    messagingSenderId: '286337204652',
    projectId: 'smarttravel-b1d56',
    storageBucket: 'smarttravel-b1d56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8ZKQyRwxj5z5fi5gR0kmn_BfEoxoKIY',
    appId: '1:286337204652:ios:f8e66d0b98da597347ba09',
    messagingSenderId: '286337204652',
    projectId: 'smarttravel-b1d56',
    storageBucket: 'smarttravel-b1d56.appspot.com',
    iosBundleId: 'com.example.iTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH8ZKQyRwxj5z5fi5gR0kmn_BfEoxoKIY',
    appId: '1:286337204652:ios:237fd34fb2d1bbe947ba09',
    messagingSenderId: '286337204652',
    projectId: 'smarttravel-b1d56',
    storageBucket: 'smarttravel-b1d56.appspot.com',
    iosBundleId: 'com.example.iTour.RunnerTests',
  );
}
